RST := \033[m
BLD := \033[1m
RED := \033[31m
GRN := \033[32m
YLW := \033[33m
BLU := \033[34m
EOL := \n

URL ?= https://xcodereleases.com/data.json

all: matrix.json
	@printf '${BLD}${RED}make: *** [$@]${RST}${EOL}'
.PHONY: all

clean:
	@printf '${BLD}${RED}make: *** [$@]${RST}${EOL}'
	@printf '${BLD}${YLW}$$${RST} '
	rm -fv ./data.json ./matrix.json
.PHONY: clean

data.json:
	@printf '${BLD}${RED}make: *** [$@]${RST}${EOL}'
	@printf '${BLD}${YLW}$$${RST} '
	wget -O ./data.json '${URL}'

matrix.json: filter.jq data.json
	jq -cf ./filter.jq ./data.json > ./matrix.json
